# Generated by Django 3.0.7 on 2020-07-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
